cape_root: "${CAPE_ROOT}"
smpl_root: "${SMPL_ROOT}"

gt_type: "unclothed"

tracker:
  name: "easymocap"
  mode: "auto"

  prediction_roots:
    - "${EASYMOCAP_RESULTS}/AutoRedo/Run1/GT"
    - "${EASYMOCAP_RESULTS}/AutoRedo/Run2/SV"
    - "${EASYMOCAP_RESULTS}/AutoRedo/Run3/SV"

  sequence_dir_format: "{subject}_{sequence}"
  prediction_subdir: "meshes"

metrics:
  - mpvpe
  - per_frame_mpvpe
  - centroid_aligned_mpvpe
  - per_frame_centroid_aligned_mpvpe
  - pa_mpvpe
  - per_frame_pa_mpvpe
  - mpjpe
  - per_frame_mpjpe
  - pelvis_aligned_mpjpe
  - per_frame_pelvis_aligned_mpjpe
  - pa_mpjpe
  - per_frame_pa_mpjpe
  - accel_error
  - per_frame_accel_error

output:
  dir: "benchmark/results/auto/SV"
  summary_file: "easymocap_auto_SV.csv"

sequences:
  - subject: "00096"
    gender: "male"
    sequence: "jerseyshort_shoulders_mill"

  - subject: "00096"
    gender: "male"
    sequence: "shirtlong_punching"

  - subject: "00145"
    gender: "male"
    sequence: "shortlong_twist_tilt_left"

  - subject: "00215"
    gender: "male"
    sequence: "poloshort_bend_back_and_front"

  - subject: "00215"
    gender: "male"
    sequence: "shortlong_tilt_twist_left"